# site settings
title: Joel Tanzi
subtitle: Content Writer
email: joel@jabaradev.com
description: High-quality SEO content
baseurl: "" # the subpath of your site, e.g. /blog
url: 
author: Joel Tanzi
street_address: 
city:
state: 
zip_code: 
country: United States of America
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/joeltanzi/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/joel_tanzi

# build settings
markdown: kramdown

sass:
  style: compressed
